### ISSUE TITLE
More support for torrent sites?

### ISSUE THREAD

**Issue by cottontails2** [jsEveryDay/real-debrid_downloader_player#3]
Can you add support for 1337x.to and rarbg.to so i can have magnet links go straight to real-debrid?

**Comment by jsEveryDay** [comment]
Any site with a magnet link is supported. You should see RD icon next to the magnet link.

I tested rarbg and it works as expected. Make sure you visit real-debrid.com/torrents after clicking the RD icon.

**Comment by cottontails2** [comment]
It doesn't seem to work with 1337x at all i don't see any RD icons, that is the main site i use for torrents.

Edit: I must have done something wrong, i re-made the script and it works perfectly now, thanks for the help :)
